spring:
  application:
    name: merchant-project
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/merchant
      #uri: mongodb://47.94.33.237:27017/merchant
      auto-index-creation: true
server:
  port: 8084

user:
  privilege:
      addPrivilegeToUser: http://127.0.0.1:8081/admin/privilege/addPrivilegeToUser
